---
title: "Weather of NYC Airports in 2010"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: simplex
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r clean data, include=FALSE}
data("ny_noaa")

airport = filter(ny_noaa, id %in% c("USW00094789", "USW00014732"),
                 date >= as.Date("2010-01-01")) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(name = recode(id, USW00094789 = "JFK", 
                        USW00014732 = "Laguardia"),
         prcp = prcp / 10,
         tmin = as.numeric(tmin) / 10,
         tmax = as.numeric(tmax) / 10) %>%
  select(name, id, everything())
```

Column {data-width=650}
-----------------------------------------------------------------------

### Temperature Plot

```{r}
airport %>%
  mutate(text_label = str_c("Precipitation: ", prcp, "mm", 
                            "\nSnowfall: ", snow, "mm", 
                            "\nSnow depth: ", snwd, "mm")) %>% 
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~name,
          marker = list(size = 7),
          text = ~text_label) %>% 
  layout(xaxis = list(title = "Minimum daily temperature (C)"), 
         yaxis = list(title = "Maximum daily temperature (C)")
         )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Monthly Cumulative Precipitation

```{r}
airport %>%
  group_by(name, month) %>% 
  summarise(sum_prcp = sum(prcp)) %>%
  spread(key = name, value = sum_prcp) %>% 
  plot_ly(x = ~month, y = ~JFK, type = "bar", name = "JFK") %>% 
  add_trace(y = ~Laguardia, name = "Laguardia") %>% 
  layout(xaxis = list(title = "Month", showgrid = F), 
         yaxis = list(title = "Culmulative precipitation \n(mm)")
         )
```

### Maximum teperature distribution by month

```{r}
airport %>%
  plot_ly(y = ~tmax, color = ~month, type = "box") %>% 
  layout(xaxis = list(title = "Month", showgrid = F), 
         yaxis = list(title = "Maximum temperature (C)")
         )
```